// Hotel Sample Data with comprehensive inventory and operations data
import { 
  Product, 
  Category, 
  HotelRoom, 
  Guest, 
  Reservation, 
  HousekeepingTask,
  MenuItem,
  MenuCategory,
  MaintenanceRequest,
  Department,
  StaffMember,
  HotelInventoryType,
  Customer // Add Customer import
} from "@/types/inventory";

// Hotel Departments
export const sampleDepartments: Department[] = [
  {
    id: "dept-1",
    name: "Housekeeping",
    description: "Room cleaning and maintenance",
    manager: "Sarah Johnson",
    budget: 50000,
    monthlyCosts: 12000,
    inventoryAllocated: ["prod-1", "prod-2", "prod-3", "prod-4"],
    staffCount: 15,
    isActive: true,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: "dept-2",
    name: "Food & Beverage",
    description: "Restaurant, bar, and room service operations",
    manager: "Marco Rodriguez",
    budget: 80000,
    monthlyCosts: 25000,
    inventoryAllocated: ["prod-10", "prod-11", "prod-12", "prod-13"],
    staffCount: 25,
    isActive: true,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: "dept-3",
    name: "Front Office",
    description: "Guest services and reception",
    manager: "Emily Chen",
    budget: 30000,
    monthlyCosts: 8000,
    inventoryAllocated: ["prod-20", "prod-21"],
    staffCount: 12,
    isActive: true,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: "dept-4",
    name: "Maintenance",
    description: "Property maintenance and engineering",
    manager: "Robert Taylor",
    budget: 40000,
    monthlyCosts: 10000,
    inventoryAllocated: ["prod-30", "prod-31", "prod-32"],
    staffCount: 8,
    isActive: true,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
];

// Hotel Categories
export const sampleHotelCategories: Category[] = [
  {
    id: "cat-1",
    name: "Housekeeping Supplies",
    description: "Cleaning supplies and room amenities",
    color: "#3B82F6",
    hotelInventoryType: "housekeeping",
    departmentResponsible: "housekeeping",
    storageLocation: "Housekeeping Storage - Level B1",
    restockFrequency: "weekly",
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: "cat-2",
    name: "Room Amenities",
    description: "In-room guest amenities and supplies",
    color: "#10B981",
    hotelInventoryType: "amenities",
    departmentResponsible: "housekeeping",
    storageLocation: "Amenities Storage - Level 2",
    restockFrequency: "daily",
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: "cat-3",
    name: "Food & Beverage",
    description: "Restaurant and bar inventory",
    color: "#F59E0B",
    hotelInventoryType: "food_beverage",
    departmentResponsible: "food_service",
    storageLocation: "Kitchen Storage - Level 1",
    restockFrequency: "daily",
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: "cat-4",
    name: "Maintenance Supplies",
    description: "Tools and materials for property maintenance",
    color: "#EF4444",
    hotelInventoryType: "maintenance",
    departmentResponsible: "maintenance",
    storageLocation: "Maintenance Workshop - Level B1",
    restockFrequency: "monthly",
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: "cat-5",
    name: "Laundry Supplies",
    description: "Laundry detergents and fabric care",
    color: "#8B5CF6",
    hotelInventoryType: "laundry",
    departmentResponsible: "housekeeping",
    storageLocation: "Laundry Room - Level B1",
    restockFrequency: "weekly",
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: "cat-6",
    name: "Office Supplies",
    description: "Administrative and office materials",
    color: "#6B7280",
    hotelInventoryType: "office_supplies",
    departmentResponsible: "front_desk",
    storageLocation: "Admin Office - Level 1",
    restockFrequency: "monthly",
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
];

// Hotel Products/Inventory
export const sampleHotelProducts: Product[] = [
  // Housekeeping Supplies
  {
    id: "prod-1",
    name: "Premium Bathroom Cleaner",
    description: "Professional-grade bathroom cleaning solution",
    sku: "HK-001",
    categoryId: "cat-1",
    price: 15.99,
    costPrice: 8.50,
    stockQuantity: 45,
    lowStockThreshold: 10,
    supplier: "CleanCorp Hospitality",
    hotelInventoryType: "housekeeping",
    unit: "bottle",
    brand: "CleanPro",
    location: "Housekeeping Storage - Shelf A3",
    isPerishable: false,
    minimumOrderQuantity: 24,
    isActive: true,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: "prod-2",
    name: "Luxury Bath Towels",
    description: "100% Egyptian cotton bath towels, 600 GSM",
    sku: "HK-002",
    categoryId: "cat-2",
    price: 45.00,
    costPrice: 25.00,
    stockQuantity: 120,
    lowStockThreshold: 30,
    supplier: "Luxury Linens Ltd",
    hotelInventoryType: "amenities",
    unit: "piece",
    brand: "Royal Cotton",
    location: "Linen Storage - Rack B",
    isPerishable: false,
    minimumOrderQuantity: 50,
    isActive: true,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: "prod-3",
    name: "Microfiber Cleaning Cloths",
    description: "High-quality microfiber cloths for dusting",
    sku: "HK-003",
    categoryId: "cat-1",
    price: 2.99,
    costPrice: 1.50,
    stockQuantity: 200,
    lowStockThreshold: 50,
    supplier: "CleanCorp Hospitality",
    hotelInventoryType: "housekeeping",
    unit: "piece",
    brand: "MicroClean",
    location: "Housekeeping Storage - Bin C",
    isPerishable: false,
    minimumOrderQuantity: 100,
    isActive: true,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: "prod-4",
    name: "Vacuum Cleaner Bags",
    description: "Compatible with Hoover commercial vacuums",
    sku: "HK-004",
    categoryId: "cat-1",
    price: 12.99,
    costPrice: 7.00,
    stockQuantity: 25,
    lowStockThreshold: 8,
    supplier: "Hotel Equipment Co",
    hotelInventoryType: "housekeeping",
    unit: "pack",
    brand: "Hoover",
    location: "Housekeeping Storage - Shelf A1",
    isPerishable: false,
    minimumOrderQuantity: 20,
    isActive: true,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: "prod-5",
    name: "Luxury Shampoo",
    description: "Premium hotel amenity shampoo 30ml bottles",
    sku: "AM-001",
    categoryId: "cat-2",
    price: 3.50,
    costPrice: 1.75,
    stockQuantity: 500,
    lowStockThreshold: 100,
    supplier: "Boutique Amenities",
    hotelInventoryType: "amenities",
    unit: "bottle",
    brand: "Serenity Spa",
    location: "Amenities Storage - Shelf D2",
    isPerishable: true,
    expiryDate: "2026-12-31",
    minimumOrderQuantity: 200,
    isActive: true,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  // Food & Beverage Items
  {
    id: "prod-10",
    name: "Organic Coffee Beans",
    description: "Premium Colombian coffee beans",
    sku: "FB-001",
    categoryId: "cat-3",
    price: 18.50,
    costPrice: 12.00,
    stockQuantity: 35,
    lowStockThreshold: 10,
    supplier: "Gourmet Coffee Co",
    hotelInventoryType: "food_beverage",
    unit: "kg",
    brand: "Mountain Peak",
    location: "Kitchen Storage - Dry Goods",
    isPerishable: true,
    expiryDate: "2025-09-15",
    batchNumber: "KB2024-07",
    minimumOrderQuantity: 20,
    isActive: true,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: "prod-11",
    name: "Fresh Salmon Fillets",
    description: "Atlantic salmon fillets, restaurant quality",
    sku: "FB-002",
    categoryId: "cat-3",
    price: 28.00,
    costPrice: 18.00,
    stockQuantity: 15,
    lowStockThreshold: 5,
    supplier: "Ocean Fresh Seafood",
    hotelInventoryType: "food_beverage",
    unit: "kg",
    brand: "Atlantic Gold",
    location: "Kitchen Storage - Refrigerator A",
    isPerishable: true,
    expiryDate: "2025-07-20",
    batchNumber: "SF2024-07-15",
    minimumOrderQuantity: 10,
    isActive: true,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: "prod-12",
    name: "Premium Red Wine",
    description: "Cabernet Sauvignon 2021, perfect for dinner service",
    sku: "FB-003",
    categoryId: "cat-3",
    price: 45.00,
    costPrice: 28.00,
    stockQuantity: 48,
    lowStockThreshold: 12,
    supplier: "Vineyard Selections",
    hotelInventoryType: "food_beverage",
    unit: "bottle",
    brand: "Château Margaux",
    location: "Wine Cellar - Rack C",
    isPerishable: false,
    minimumOrderQuantity: 24,
    isActive: true,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  // Maintenance Supplies
  {
    id: "prod-30",
    name: "LED Light Bulbs",
    description: "Energy-efficient LED bulbs 15W warm white",
    sku: "MT-001",
    categoryId: "cat-4",
    price: 8.99,
    costPrice: 5.50,
    stockQuantity: 100,
    lowStockThreshold: 25,
    supplier: "Electrical Supplies Inc",
    hotelInventoryType: "maintenance",
    unit: "piece",
    brand: "EcoLight",
    location: "Maintenance Storage - Electrical Section",
    isPerishable: false,
    minimumOrderQuantity: 50,
    isActive: true,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: "prod-31",
    name: "Air Filter Cartridges",
    description: "HVAC system replacement filters",
    sku: "MT-002",
    categoryId: "cat-4",
    price: 25.00,
    costPrice: 15.00,
    stockQuantity: 20,
    lowStockThreshold: 5,
    supplier: "HVAC Solutions",
    hotelInventoryType: "maintenance",
    unit: "piece",
    brand: "AirPure",
    location: "Maintenance Storage - HVAC Section",
    isPerishable: false,
    minimumOrderQuantity: 12,
    isActive: true,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
];

// Hotel Rooms
export const sampleHotelRooms: HotelRoom[] = [
  {
    id: "room-101",
    roomNumber: "101",
    roomType: "standard",
    floor: 1,
    capacity: 2,
    basePrice: 120.00,
    status: "available",
    amenities: ["wifi", "tv", "air_conditioning", "safe", "minibar"],
    lastCleaned: new Date(Date.now() - 2 * 60 * 60 * 1000).toISOString(), // 2 hours ago
    nextMaintenance: new Date(Date.now() + 7 * 24 * 60 * 60 * 1000).toISOString(), // 1 week from now
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: "room-102",
    roomNumber: "102",
    roomType: "standard",
    floor: 1,
    capacity: 2,
    basePrice: 120.00,
    status: "occupied",
    amenities: ["wifi", "tv", "air_conditioning", "safe", "minibar"],
    lastCleaned: new Date(Date.now() - 24 * 60 * 60 * 1000).toISOString(), // 1 day ago
    occupancy: {
      guestName: "John Smith",
      checkIn: new Date(Date.now() - 24 * 60 * 60 * 1000).toISOString(),
      checkOut: new Date(Date.now() + 48 * 60 * 60 * 1000).toISOString(),
      guestCount: 2,
    },
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: "room-201",
    roomNumber: "201",
    roomType: "deluxe",
    floor: 2,
    capacity: 3,
    basePrice: 180.00,
    status: "cleaning",
    amenities: ["wifi", "tv", "air_conditioning", "safe", "minibar", "balcony", "coffee_machine"],
    lastCleaned: new Date(Date.now() - 30 * 60 * 1000).toISOString(), // 30 minutes ago
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: "room-301",
    roomNumber: "301",
    roomType: "suite",
    floor: 3,
    capacity: 4,
    basePrice: 350.00,
    status: "maintenance",
    amenities: ["wifi", "tv", "air_conditioning", "safe", "minibar", "balcony", "coffee_machine", "living_room", "kitchen"],
    lastCleaned: new Date(Date.now() - 48 * 60 * 60 * 1000).toISOString(), // 2 days ago
    nextMaintenance: new Date().toISOString(), // Maintenance now
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
];

// Sample Guests
export const sampleGuests: Guest[] = [
  {
    id: "guest-1",
    firstName: "John",
    lastName: "Smith",
    email: "john.smith@email.com",
    phone: "+1-555-0123",
    nationality: "American",
    passportNumber: "US123456789",
    vipStatus: "gold",
    preferences: ["late_checkout", "high_floor", "quiet_room"],
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: "guest-2",
    firstName: "Maria",
    lastName: "Garcia",
    email: "maria.garcia@email.com",
    phone: "+34-612-345-678",
    nationality: "Spanish",
    passportNumber: "ES987654321",
    vipStatus: "platinum",
    preferences: ["sea_view", "champagne_arrival", "flower_decoration"],
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: "guest-3",
    firstName: "Hiroshi",
    lastName: "Tanaka",
    email: "h.tanaka@email.com",
    phone: "+81-90-1234-5678",
    nationality: "Japanese",
    passportNumber: "JP456789123",
    vipStatus: "silver",
    preferences: ["japanese_breakfast", "early_checkin", "no_smoking_floor"],
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
];

// Sample Reservations
export const sampleReservations: Reservation[] = [
  {
    id: "res-1",
    guestId: "guest-1",
    roomId: "room-102",
    reservationNumber: "HTL-2024-001",
    checkInDate: new Date(Date.now() - 24 * 60 * 60 * 1000).toISOString(),
    checkOutDate: new Date(Date.now() + 48 * 60 * 60 * 1000).toISOString(),
    numberOfGuests: 2,
    totalAmount: 360.00, // 3 nights
    depositPaid: 120.00,
    status: "checked_in",
    bookingSource: "direct",
    createdAt: new Date(Date.now() - 7 * 24 * 60 * 60 * 1000).toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: "res-2",
    guestId: "guest-2",
    roomId: "room-301",
    reservationNumber: "HTL-2024-002",
    checkInDate: new Date(Date.now() + 7 * 24 * 60 * 60 * 1000).toISOString(),
    checkOutDate: new Date(Date.now() + 10 * 24 * 60 * 60 * 1000).toISOString(),
    numberOfGuests: 2,
    totalAmount: 1050.00, // 3 nights suite
    depositPaid: 350.00,
    status: "confirmed",
    specialRequests: "Champagne and flowers in room upon arrival",
    bookingSource: "online",
    createdAt: new Date(Date.now() - 14 * 24 * 60 * 60 * 1000).toISOString(),
    updatedAt: new Date().toISOString(),
  },
];

// Sample Housekeeping Tasks
export const sampleHousekeepingTasks: HousekeepingTask[] = [
  {
    id: "hk-task-1",
    roomNumber: "201",
    taskType: "cleaning",
    priority: "high",
    status: "in_progress",
    assignedTo: "Maria Rodriguez",
    estimatedDuration: 45,
    notes: "Deep cleaning required after checkout",
    itemsUsed: [
      { productId: "prod-1", quantity: 1 },
      { productId: "prod-2", quantity: 3 },
      { productId: "prod-3", quantity: 5 },
    ],
    createdAt: new Date(Date.now() - 60 * 60 * 1000).toISOString(),
    scheduledFor: new Date().toISOString(),
  },
  {
    id: "hk-task-2",
    roomNumber: "301",
    taskType: "maintenance",
    priority: "urgent",
    status: "pending",
    estimatedDuration: 120,
    notes: "Air conditioning unit not working properly",
    createdAt: new Date(Date.now() - 30 * 60 * 1000).toISOString(),
    scheduledFor: new Date(Date.now() + 2 * 60 * 60 * 1000).toISOString(),
  },
];

// Sample Menu Categories
export const sampleMenuCategories: MenuCategory[] = [
  {
    id: "menu-cat-1",
    name: "Appetizers",
    description: "Delicious starters to begin your meal",
    type: "appetizer",
    isActive: true,
    displayOrder: 1,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: "menu-cat-2",
    name: "Main Courses",
    description: "Hearty main dishes featuring fresh, local ingredients",
    type: "food",
    isActive: true,
    displayOrder: 2,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: "menu-cat-3",
    name: "Beverages",
    description: "Refreshing drinks and premium cocktails",
    type: "beverage",
    isActive: true,
    displayOrder: 3,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
];

// Sample Menu Items
export const sampleMenuItems: MenuItem[] = [
  {
    id: "menu-item-1",
    name: "Grilled Atlantic Salmon",
    description: "Fresh salmon fillet with lemon herb butter, served with seasonal vegetables",
    categoryId: "menu-cat-2",
    price: 28.00,
    costPrice: 18.00,
    preparationTime: 25,
    allergens: ["fish"],
    dietaryInfo: ["gluten-free"],
    ingredients: [
      { productId: "prod-11", quantity: 0.2, unit: "kg" },
    ],
    isAvailable: true,
    popularityScore: 85,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: "menu-item-2",
    name: "House Wine Selection",
    description: "Our sommelier's choice of premium red wine",
    categoryId: "menu-cat-3",
    price: 12.00,
    costPrice: 8.00,
    preparationTime: 2,
    allergens: ["sulfites"],
    dietaryInfo: [],
    ingredients: [
      { productId: "prod-12", quantity: 0.15, unit: "bottle" },
    ],
    isAvailable: true,
    popularityScore: 70,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
];

// Sample Maintenance Requests
export const sampleMaintenanceRequests: MaintenanceRequest[] = [
  {
    id: "maint-1",
    roomNumber: "301",
    area: "guest_room",
    issueType: "hvac",
    priority: "high",
    description: "Air conditioning unit not cooling properly, guest complaint",
    reportedBy: "Front Desk",
    assignedTo: "Robert Taylor",
    status: "assigned",
    estimatedCost: 150.00,
    reportedAt: new Date(Date.now() - 2 * 60 * 60 * 1000).toISOString(),
    scheduledFor: new Date(Date.now() + 1 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: "maint-2",
    area: "lobby",
    issueType: "electrical",
    priority: "medium",
    description: "Two ceiling lights flickering in main lobby area",
    reportedBy: "Housekeeping",
    status: "reported",
    estimatedCost: 75.00,
    reportedAt: new Date(Date.now() - 4 * 60 * 60 * 1000).toISOString(),
  },
];

// Sample Staff Members
export const sampleStaffMembers: StaffMember[] = [
  {
    id: "staff-1",
    employeeId: "EMP-001",
    firstName: "Sarah",
    lastName: "Johnson",
    departmentId: "dept-1",
    position: "Housekeeping Manager",
    email: "sarah.johnson@hotel.com",
    phone: "+1-555-0101",
    shiftSchedule: "Day Shift (6AM-2PM)",
    accessLevel: "manager",
    hireDate: "2023-01-15",
    isActive: true,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: "staff-2",
    employeeId: "EMP-002",
    firstName: "Maria",
    lastName: "Rodriguez",
    departmentId: "dept-1",
    position: "Room Attendant",
    email: "maria.rodriguez@hotel.com",
    phone: "+1-555-0102",
    shiftSchedule: "Day Shift (7AM-3PM)",
    accessLevel: "basic",
    hireDate: "2023-03-20",
    isActive: true,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: "staff-3",
    employeeId: "EMP-003",
    firstName: "Marco",
    lastName: "Rodriguez",
    departmentId: "dept-2",
    position: "F&B Manager",
    email: "marco.rodriguez@hotel.com",
    phone: "+1-555-0103",
    shiftSchedule: "Split Shift (10AM-2PM, 6PM-10PM)",
    accessLevel: "manager",
    hireDate: "2022-11-10",
    isActive: true,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
];

// Sample Hotel Customers
export const sampleHotelCustomers: Customer[] = [
  {
    id: "cust-1",
    name: "John Smith",
    email: "john.smith@email.com",
    phone: "+1-555-0123",
    address: "123 Main Street, New York, NY 10001",
    customerType: "guest",
    nationality: "American",
    passportNumber: "US123456789",
    loyaltyMembership: "gold",
    totalStayNights: 45,
    totalSpent: 12500.00,
    lastVisit: new Date(Date.now() - 30 * 24 * 60 * 60 * 1000).toISOString(),
    preferences: ["late_checkout", "high_floor", "quiet_room", "feather_pillows"],
    emergencyContact: {
      name: "Jane Smith",
      phone: "+1-555-0124",
      relationship: "spouse"
    },
    notes: "Prefers room with city view. Allergic to shellfish.",
    createdAt: new Date(Date.now() - 365 * 24 * 60 * 60 * 1000).toISOString(),
    updatedAt: new Date().toISOString(),
    isActive: true,
  },
  {
    id: "cust-2",
    name: "Maria Garcia",
    email: "maria.garcia@email.com",
    phone: "+34-612-345-678",
    address: "Calle Mayor 15, Madrid, Spain",
    customerType: "guest",
    nationality: "Spanish",
    passportNumber: "ES987654321",
    loyaltyMembership: "platinum",
    totalStayNights: 120,
    totalSpent: 35000.00,
    lastVisit: new Date(Date.now() - 7 * 24 * 60 * 60 * 1000).toISOString(),
    preferences: ["sea_view", "champagne_arrival", "flower_decoration", "spa_services"],
    emergencyContact: {
      name: "Carlos Garcia",
      phone: "+34-612-345-679",
      relationship: "husband"
    },
    notes: "VIP guest. Celebrates anniversary every year. Prefers Spanish cuisine.",
    createdAt: new Date(Date.now() - 2 * 365 * 24 * 60 * 60 * 1000).toISOString(),
    updatedAt: new Date().toISOString(),
    isActive: true,
  },
  {
    id: "cust-3",
    name: "TechCorp International",
    email: "bookings@techcorp.com",
    phone: "+1-800-TECH-123",
    address: "456 Business Ave, San Francisco, CA 94105",
    customerType: "corporate",
    companyName: "TechCorp International",
    loyaltyMembership: "platinum",
    creditLimit: 50000.00,
    paymentTerms: "Net 30",
    totalStayNights: 365,
    totalSpent: 125000.00,
    lastVisit: new Date(Date.now() - 5 * 24 * 60 * 60 * 1000).toISOString(),
    preferences: ["corporate_rate", "meeting_rooms", "business_center", "express_checkout"],
    notes: "Corporate account with monthly billing. Frequently books for conferences.",
    createdAt: new Date(Date.now() - 3 * 365 * 24 * 60 * 60 * 1000).toISOString(),
    updatedAt: new Date().toISOString(),
    isActive: true,
  },
  {
    id: "cust-4",
    name: "Hiroshi Tanaka",
    email: "h.tanaka@email.com",
    phone: "+81-90-1234-5678",
    address: "2-1-1 Shibuya, Tokyo, Japan",
    customerType: "guest",
    nationality: "Japanese",
    passportNumber: "JP456789123",
    loyaltyMembership: "silver",
    totalStayNights: 25,
    totalSpent: 8500.00,
    lastVisit: new Date(Date.now() - 60 * 24 * 60 * 60 * 1000).toISOString(),
    preferences: ["japanese_breakfast", "early_checkin", "no_smoking_floor", "traditional_amenities"],
    emergencyContact: {
      name: "Yuki Tanaka",
      phone: "+81-90-1234-5679",
      relationship: "daughter"
    },
    notes: "Business traveler. Prefers Japanese-style service and amenities.",
    createdAt: new Date(Date.now() - 18 * 30 * 24 * 60 * 60 * 1000).toISOString(),
    updatedAt: new Date().toISOString(),
    isActive: true,
  },
  {
    id: "cust-5",
    name: "Elite Travel Agency",
    email: "reservations@elitetravel.com",
    phone: "+44-20-7123-4567",
    address: "10 Downing Street, London, UK",
    customerType: "travel_agency",
    companyName: "Elite Travel Agency",
    loyaltyMembership: "gold",
    creditLimit: 75000.00,
    paymentTerms: "Net 15",
    totalStayNights: 500,
    totalSpent: 200000.00,
    lastVisit: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000).toISOString(),
    preferences: ["group_rates", "tour_packages", "transportation_arrangements", "bulk_reservations"],
    notes: "High-volume travel agency. Handles luxury tour groups and corporate events.",
    createdAt: new Date(Date.now() - 5 * 365 * 24 * 60 * 60 * 1000).toISOString(),
    updatedAt: new Date().toISOString(),
    isActive: true,
  },
];

export const getHotelInventoryTypeColor = (type: HotelInventoryType): string => {
  const colors = {
    room: "#3B82F6",           // Blue
    housekeeping: "#10B981",   // Green
    food_beverage: "#F59E0B",  // Amber
    amenities: "#8B5CF6",      // Purple
    maintenance: "#EF4444",    // Red
    laundry: "#06B6D4",        // Cyan
    office_supplies: "#6B7280", // Gray
    guest_supplies: "#EC4899", // Pink
  };
  return colors[type] || "#6B7280";
};

export const getHotelInventoryTypeLabel = (type: HotelInventoryType): string => {
  const labels = {
    room: "Room Inventory",
    housekeeping: "Housekeeping",
    food_beverage: "Food & Beverage",
    amenities: "Amenities",
    maintenance: "Maintenance",
    laundry: "Laundry",
    office_supplies: "Office Supplies",
    guest_supplies: "Guest Supplies",
  };
  return labels[type] || type;
};

export const getCustomerTypeColor = (type: string): string => {
  const colors = {
    guest: "#3B82F6",           // Blue
    corporate: "#10B981",       // Green
    travel_agency: "#F59E0B",   // Amber
    regular: "#8B5CF6",         // Purple
  };
  return colors[type as keyof typeof colors] || "#6B7280";
};

export const getLoyaltyMembershipColor = (membership: string): string => {
  const colors = {
    none: "#6B7280",           // Gray
    bronze: "#CD7F32",         // Bronze
    silver: "#C0C0C0",         // Silver
    gold: "#FFD700",           // Gold
    platinum: "#E5E4E2",       // Platinum
  };
  return colors[membership as keyof typeof colors] || "#6B7280";
};
